import React, { useState } from 'react';
import { PROFILE_LIMITS } from '../../utils/profileDraft';

export default function EmployeeProfileWorkspace({ AuthenticatedAvatar, CHAT_DENSITIES, CHAT_TEXT_SIZES, CHAT_THEMES, ChatAppearanceSettings, avatarInputRef, avatarUrl, changeMyPassword, chatLocalSettings, formatVisibleLogin, getOptionLabel, handleLogout, isAdmin, isEnglishInterface, passwordForm, profileForm, profilePreview, profileViewLogin, receivedArchivesPanel, removeAvatar, saveMyProfile, setActiveTab, setPasswordForm, setProfileViewLogin, setSelectedEmail, t, toggleDialogToolSetting, toggleFeedToolSetting, updateChatUiSetting, updateProfileField, user, profileState, profileDirty, loadProfile, openProfileCard, restoreDraft, discardChanges, resolveConflict, passwordBusy, passwordError }) {
  const [showPasswords, setShowPasswords] = useState(false);
  const c = (ru, en) => isEnglishInterface ? en : ru;
  const serviceFields = [['full_name', 'fullName'], ['position', 'position'], ['department', 'department'], ['room', 'room'], ['phone', 'internalPhone'], ['external_phone', 'externalPhone']];
  const dialogTools = [['showConversationMenu', 'showConversationMenuTitle', 'showConversationMenuHint'], ['showExtraMessageActions', 'showExtraMessageActionsTitle', 'showExtraMessageActionsHint'], ['showChatTemplates', 'showChatTemplatesTitle', 'showChatTemplatesHint'], ['showDialogMediaPanel', 'showDialogMediaPanelTitle', 'showDialogMediaPanelHint'], ['showDialogDateJump', 'showDialogDateJumpTitle', 'showDialogDateJumpHint'], ['showDialogFilters', 'showDialogFiltersTitle', 'showDialogFiltersHint']];
  const feedTools = [['showFeedCategorySelect', 'showFeedCategorySelectTitle', 'showFeedCategorySelectHint'], ['showFeedFilters', 'showFeedFiltersTitle', 'showFeedFiltersHint']];
  const statusText = value => value === 'Работа' ? c('Работа', 'Work') : value;
  const toolRows = (items, toggle) => items.map(([key, title, hint]) => <label key={key} className="profile-toggle-row"><input type="checkbox" checked={chatLocalSettings[key] === true} onChange={() => toggle(key)} /><span><strong>{t(title)}</strong><small>{t(hint)}</small></span></label>);
  const photoControls = <><div className="profile-preview-avatar"><AuthenticatedAvatar src={avatarUrl} alt={t('profilePhoto')} fallback={<span>{String(profileForm.full_name || user.username || '?').slice(0, 1).toUpperCase()}</span>} /></div><p>{c('PNG, JPG или WEBP до 5 МБ. После кадрирования: 256 × 256, до 1 МБ. Фото сохраняется отдельно.', 'PNG, JPG or WEBP up to 5 MB. Cropped photo: 256 × 256, up to 1 MB. Photos save separately.')}</p><div className="avatar-actions-row"><button type="button" disabled={profileState.avatarBusy} onClick={() => avatarInputRef.current?.click()}>{t('changePhoto')}</button><button type="button" onClick={removeAvatar} disabled={!avatarUrl || profileState.avatarBusy}>{t('removePhoto')}</button></div>{profileState.avatarBusy && <p role="status">{c('Сохранение фотографии…', 'Saving photo…')}</p>}</>;
  if (profileViewLogin) return <div className="profile-workspace"><div className="profile-preview-card">
    <button type="button" className="back-to-chat-btn profile-preview-back" onClick={() => setProfileViewLogin('')}>← {t('myProfile')}</button>
    {profileState.previewLoading && <p role="status">{t('loading')}…</p>}
    {profileState.previewError && <div role="alert"><p>{profileState.previewError}</p><button type="button" onClick={() => openProfileCard(profileViewLogin)}>{c('Повторить', 'Retry')}</button></div>}
    {profilePreview && <><div className="profile-preview-hero"><div className="profile-preview-avatar"><AuthenticatedAvatar src={profilePreview.avatar} alt={t('profilePhoto')} fallback={<span>{String(profilePreview.full_name || profilePreview.login || '?').slice(0, 1).toUpperCase()}</span>} /></div><div className="profile-preview-identity"><span className="profile-preview-kicker">{t('internalProfile')}</span><h3>{profilePreview.full_name || profilePreview.login}</h3><p>{profilePreview.login}</p><div className="profile-preview-badges">{profilePreview.statusText && <span className="profile-status-pill">{statusText(profilePreview.statusText)}</span>}{profilePreview.department && <span>{profilePreview.department}</span>}</div></div></div>
    <div className="profile-preview-grid">{serviceFields.slice(1).map(([key, label]) => <div key={key}><strong>{t(label)}</strong><p>{profilePreview[key] ? ['phone', 'external_phone'].includes(key) ? <a href={`tel:${String(profilePreview[key]).replace(/[^+\d]/g, '')}`}>{profilePreview[key]}</a> : profilePreview[key] : '—'}</p></div>)}<div className="profile-preview-wide"><strong>{t('bio')}</strong><p className="profile-bio-text">{profilePreview.bio || '—'}</p></div><div><strong>{t('website')}</strong><p><a href="https://web3.nioch.nsc.ru/nioch/index.php/ru/" target="_blank" rel="noopener noreferrer">НИОХ СО РАН</a></p></div></div>
    {!sameAccount(user.username, profilePreview.login) && <div className="profile-preview-actions"><button type="button" onClick={() => { setSelectedEmail(profilePreview.login); setProfileViewLogin(''); setActiveTab('chat'); }}>{t('openDialog')}</button></div>}</>}
  </div></div>;
  return <div className="profile-workspace">
    {profileState.loading && <p role="status">{t('loading')}…</p>}
    {profileState.error && <div className="profile-feedback" role="alert"><p>{profileState.error}</p><button type="button" disabled={profileState.loading} onClick={loadProfile}>{c('Обновить профиль', 'Refresh profile')}</button></div>}
    {profileState.storageError && <p role="alert">{c('Не удалось сохранить черновик в браузере. Не закрывайте страницу до сохранения на сервере.', 'Could not save the draft in this browser. Keep this page open until the server confirms saving.')}</p>}
    {profileState.message && <p role="status">{profileState.message}</p>}
    {profileState.draft && <div className="profile-feedback"><p>{c('Найден несохранённый черновик личных сведений.', 'An unsaved personal profile draft was found.')}</p><button type="button" onClick={restoreDraft}>{c('Восстановить черновик', 'Restore draft')}</button><button type="button" onClick={discardChanges}>{c('Удалить черновик', 'Discard draft')}</button></div>}
    {profileState.conflict && <section className="profile-panel profile-conflict" role="alert"><h3>{c('Профиль изменён в другом окне', 'Profile changed in another window')}</h3><p>{c('Сравните значения. Применение вашего текста потребует нового сохранения.', 'Compare the values. Keeping your text requires saving again.')}</p><div className="profile-comparison">{['statusText', 'bio'].map(key => <div key={key}><h4>{t(key === 'bio' ? 'bio' : 'status')}</h4><strong>{c('На сервере:', 'On the server:')}</strong><p className="profile-bio-text">{profileState.conflict[key] || '—'}</p><strong>{c('Ваш текст:', 'Your text:')}</strong><p className="profile-bio-text">{profileForm[key] || '—'}</p></div>)}</div><button type="button" onClick={() => resolveConflict(true)}>{c('Принять данные сервера', 'Use server values')}</button><button type="button" onClick={() => resolveConflict(false)}>{c('Оставить мой текст', 'Keep my text')}</button></section>}
    <div className="profile-settings-grid">
      <section className="profile-panel"><h3>{c('Служебные сведения', 'Employee directory')}</h3><p>{c('Данные из справочника сотрудников. Для исправления обратитесь к администратору.', 'These details come from the employee directory. Contact an administrator to correct them.')}</p><div className="profile-form profile-form-labeled">{serviceFields.map(([key, label]) => <label key={key}><span>{t(label)}</span><input value={profileForm[key] || ''} readOnly /></label>)}<label><span>{t('login')}</span><input value={user.username} readOnly /></label></div></section>
      <section className="profile-panel"><h3>{c('Личная информация', 'Personal information')}</h3><form onSubmit={saveMyProfile} className="profile-form profile-form-labeled" aria-busy={profileState.saving}>
        <p className="profile-field-wide" role="status">{profileDirty ? c('Есть несохранённые изменения.', 'You have unsaved changes.') : c('Изменения сохраняются кнопкой ниже.', 'Use the button below to save changes.')}</p>
        {['statusText', 'bio'].map(key => <label key={key} className="profile-field-wide"><span>{t(key === 'bio' ? 'bio' : 'status')}</span>{key === 'bio' ? <textarea rows={4} value={profileForm[key]} maxLength={PROFILE_LIMITS[key]} disabled={profileState.loading} aria-invalid={Boolean(profileState.fields[key])} aria-describedby={`profile-${key}-hint`} onChange={e => updateProfileField(key, e.target.value)} /> : <input value={statusText(profileForm[key])} maxLength={PROFILE_LIMITS[key]} disabled={profileState.loading} aria-invalid={Boolean(profileState.fields[key])} aria-describedby={`profile-${key}-hint`} onChange={e => updateProfileField(key, e.target.value)} />}<small id={`profile-${key}-hint`}>{profileState.fields[key] || `${(key === 'statusText' ? statusText(profileForm[key]) : profileForm[key]).length} / ${PROFILE_LIMITS[key]}`}</small></label>)}
        <button type="submit" disabled={profileState.saving || profileState.loading || !profileDirty || Boolean(profileState.conflict)}>{profileState.saving ? c('Сохранение…', 'Saving…') : t('saveProfile')}</button><button type="button" disabled={profileState.saving || !profileDirty} onClick={discardChanges}>{c('Отменить изменения', 'Discard changes')}</button>
      </form></section>
      <section className="profile-panel"><h3>{t('profilePhoto')}</h3>{photoControls}</section>
      <section className="profile-panel"><h3>{t('appearance')}</h3><p>{c('Эти настройки сохраняются автоматически для вашего аккаунта.', 'These settings save automatically for your account.')}</p><ChatAppearanceSettings settings={chatLocalSettings} onChange={updateChatUiSetting} isEnglish={isEnglishInterface} /><div className="chat-appearance-controls profile-appearance-controls">{[['uiTheme', 'theme', CHAT_THEMES, 'light'], ['uiDensity', 'density', CHAT_DENSITIES, 'regular'], ['uiTextSize', 'textSize', CHAT_TEXT_SIZES, 'medium']].map(([key, label, options, fallback]) => <label key={key}><span>{t(label)}</span><select value={chatLocalSettings[key] || fallback} onChange={e => updateChatUiSetting(key, e.target.value)}>{options.map(item => <option key={item.id} value={item.id}>{getOptionLabel(item)}</option>)}</select></label>)}</div><div className="profile-chat-tools"><strong>{t('dialogTools')}</strong>{toolRows(dialogTools, toggleDialogToolSetting)}</div><div className="profile-chat-tools"><strong>{t('feedTools')}</strong>{toolRows(feedTools, toggleFeedToolSetting)}</div></section>
      <section className="profile-panel"><h3>{c('Безопасность', 'Security')}</h3><p id="profile-password-rules">{c('Новый пароль: от 8 до 256 символов, отличается от текущего. После смены потребуется повторный вход.', 'New password: 8–256 characters, different from the current password. You will need to sign in again.')}</p><form onSubmit={changeMyPassword} className="profile-password-form" aria-busy={passwordBusy}>{[['currentPassword', t('currentPassword'), 'current-password'], ['newPassword', t('newPassword'), 'new-password'], ['confirmPassword', c('Повторите новый пароль', 'Confirm new password'), 'new-password']].map(([key, label, autocomplete]) => <label key={key}><span>{label}</span><input type={showPasswords ? 'text' : 'password'} autoComplete={autocomplete} value={passwordForm[key] || ''} required minLength={key === 'currentPassword' ? undefined : 8} maxLength={256} disabled={passwordBusy} aria-describedby="profile-password-rules" onChange={e => setPasswordForm(prev => ({ ...prev, [key]: e.target.value }))} /></label>)}<label className="profile-toggle-row"><input type="checkbox" checked={showPasswords} onChange={e => setShowPasswords(e.target.checked)} /><span>{c('Показать пароли', 'Show passwords')}</span></label>{passwordError && <p role="alert">{passwordError}</p>}<button type="submit" disabled={passwordBusy}>{passwordBusy ? c('Сохранение…', 'Saving…') : t('updatePassword')}</button></form>{!isAdmin && <button type="button" className="profile-logout-btn" onClick={handleLogout}>{t('logout')}</button>}</section>
    </div>{receivedArchivesPanel}
  </div>;
}
const sameAccount = (a, b) => String(a || '').toLowerCase() === String(b || '').toLowerCase();
